In [71]:
## DataFrame

In [72]:
import numpy as np
import pandas as pd

In [73]:
## Creating DataFrame


data = {
    'Name': ['Aman', 'Riya', 'Karan', 'Sneha'],
    'Age': [31, 21, 33, 22],
    'City': ['Delhi', 'Mumbai', 'Paris', 'Bangalore'],
    'Salary': [30000, 35000, 40000, 38000]
}

df = pd.DataFrame(data)

In [74]:
data_list = [
    ['Aman', 22, 'Delhi', 30000],
    ['Riya', 21, 'Mumbai', 35000],
    ['Karan', 23, 'Jaipur', 40000],
    ['Sneha', 22, 'Bangalore', 38000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age       City  Salary
0   Aman   22      Delhi   30000
1   Riya   21     Mumbai   35000
2  Karan   23     Jaipur   40000
3  Sneha   22  Bangalore   38000

In [75]:
## Selection and indexing of dataframe

df['Name']  ##for targeting single column

0     Aman
1     Riya
2    Karan
3    Sneha
Name: Name, dtype: object

In [76]:
df[["Age","Salary"]]   ##for targeting more than one column

   Age  Salary
0   31   30000
1   21   35000
2   33   40000
3   22   38000

In [77]:
## Creating a new Column

df2["Designation"]=["Doctor","Engg","Doctor","Doctor"]
df2

    Name  Age       City  Salary Designation
0   Aman   22      Delhi   30000      Doctor
1   Riya   21     Mumbai   35000        Engg
2  Karan   23     Jaipur   40000      Doctor
3  Sneha   22  Bangalore   38000      Doctor

In [78]:
## Remove column

df2.drop('Designation',axis = 1)  ## we use [inplace = True] for permanently delete the data

    Name  Age       City  Salary
0   Aman   22      Delhi   30000
1   Riya   21     Mumbai   35000
2  Karan   23     Jaipur   40000
3  Sneha   22  Bangalore   38000

In [79]:
df2.drop(["City","Name"],axis = 1)  ### it dlts the city and name column

   Age  Salary Designation
0   22   30000      Doctor
1   21   35000        Engg
2   23   40000      Doctor
3   22   38000      Doctor

In [80]:
df2.drop(0,axis = 0)       #it dlts the oth row

    Name  Age       City  Salary Designation
1   Riya   21     Mumbai   35000        Engg
2  Karan   23     Jaipur   40000      Doctor
3  Sneha   22  Bangalore   38000      Doctor

In [81]:
# Selecting rows

df2.loc[[0,1]]   # loc is location

   Name  Age    City  Salary Designation
0  Aman   22   Delhi   30000      Doctor
1  Riya   21  Mumbai   35000        Engg

In [82]:
df.iloc[0] # iloc is index location

Name       Aman
Age          31
City      Delhi
Salary    30000
Name: 0, dtype: object

In [83]:
# Selecting subsets of rows and columns

df.loc[[0,1]][["City","Salary"]]

     City  Salary
0   Delhi   30000
1  Mumbai   35000

In [84]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Karan   33
3  Sneha   22

In [85]:
# Conditional Selection

## i want to only see those pepoles who age is more than 30

df[df["Age"]>30]

    Name  Age   City  Salary
0   Aman   31  Delhi   30000
2  Karan   33  Paris   40000

In [87]:
## i want to only see those pepoles who age is more than 30 and their city must be paris

df[(df["Age"]>30) & (df["City"] == 'Paris')]

    Name  Age   City  Salary
2  Karan   33  Paris   40000